"""VFD helper for vfd_pwm firmware.

Two responsibilities:

1) Emit `sine_q15[256]` LUT into `vfd_pwm/Src/signal_array.c`.
   This LUT is normalized (sin(2*pi*i/256) in Q15) and lives forever in flash.
   The firmware DDS does amplitude/frequency/offset at runtime, so the LUT
   never needs to be regenerated for new operating points.

2) Simulate the firmware DDS output for a chosen (fo, amp, offset, fc) and
   plot it together with its FFT, so you can validate before flashing.

Run:  python gen_signal.py
"""
import numpy as np
import matplotlib.pyplot as plt

# ---------------------------------------------------------------------------
# Hardware constants (must match my_lib.h on the MCU)
# ---------------------------------------------------------------------------
CORE_CLK_HZ       = 48_000_000
CARRIER_PERIOD_US = 50 # 20 kHz carrier
PWM_ARR           = round(CORE_CLK_HZ * CARRIER_PERIOD_US * 1e-6) - 1  # 2399
FS_HZ             = CORE_CLK_HZ // (PWM_ARR + 1) # 20000

LUT_BITS = 8
LUT_SIZE = 1 << LUT_BITS # 256
Q15_MAX  = 32767

# ---------------------------------------------------------------------------
# 1) LUT generation
# ---------------------------------------------------------------------------
def build_sine_q15():
    idx  = np.arange(LUT_SIZE, dtype=np.float64)
    sine = np.sin(2.0 * np.pi * idx / LUT_SIZE)
    q15  = np.clip(np.round(sine * Q15_MAX), -Q15_MAX - 1, Q15_MAX).astype(np.int16)
    return q15

def write_lut_c(q15, path="vfd_pwm/Src/signal_array.c", vals_per_line=8):
    indent = "    "
    with open(path, "w", encoding="utf-8") as f:
        f.write("/* Auto-generated by gen_signal.py - DO NOT EDIT BY HAND. */\n")
        f.write('#include "main.h"\n\n')
        f.write(f"/* Normalized sine LUT, Q15, {LUT_SIZE} entries.\n")
        f.write( "   sine_q15[i] = round(sin(2*pi*i/N) * 32767), i in [0, N).\n")
        f.write( "   Runtime DDS in my_lib.c applies amplitude, offset and frequency. */\n\n")
        f.write(f"const int16_t sine_q15[{LUT_SIZE}] = {{\n{indent}")
        for i, v in enumerate(q15):
            f.write(f"{int(v):6d}")
            if i < LUT_SIZE - 1:
                f.write(",")
                if (i + 1) % vals_per_line == 0:
                    f.write(f"\n{indent}")
                else:
                    f.write(" ")
        f.write("\n};\n")
    print(f"Wrote {path}  (LUT_SIZE={LUT_SIZE}, Q15)")

# ---------------------------------------------------------------------------
# 2) DDS simulation (mirrors my_lib.c)
# ---------------------------------------------------------------------------
def dds_simulate(fo_hz, amp_q15, offset_ccr, n_periods=4):
    """Reproduces exactly what the firmware does each PWM cycle.

    amp_q15 in [0, 32767] -> 0 % .. 100 % del swing maximo de CCR (= ARR/2).
    Para offset = ARR/2 y amp_q15 = 32767 se obtiene una senoide a full
    sin saturar (CCR oscila entre 0 y ARR).
    """
    lut       = build_sine_q15()
    phase_inc = int(((fo_hz * (1 << 32)) // FS_HZ)) & 0xFFFFFFFF
    n_samples = max(int(np.ceil(n_periods * FS_HZ / max(fo_hz, 1))), 256)
    # Pre-escalado igual que en el firmware (setter): amp_q15 * (ARR/2) >> 15
    amp_ccr   = (amp_q15 * (PWM_ARR // 2)) >> 15
    phase     = 0
    ccr       = np.empty(n_samples, dtype=np.int32)
    for k in range(n_samples):
        idx   = (phase >> (32 - LUT_BITS)) & (LUT_SIZE - 1)
        s     = int(lut[idx])                                 # Q15 signed
        v     = (s * amp_ccr) >> 15                           # cuentas de CCR
        c     = offset_ccr + v
        if   c < 0:           c = 0
        elif c > PWM_ARR:     c = PWM_ARR
        ccr[k] = c
        phase  = (phase + phase_inc) & 0xFFFFFFFF
    t = np.arange(n_samples) / FS_HZ
    return t, ccr

def firmware_params(fo_hz, amp_q15, offset_ccr):
    """Calcula los valores INTERNOS que generaria el firmware en my_lib.c
    al recibir (fo_hz, amp_q15, offset_ccr) por UART. Espejo exacto de los
    setters en C, util para correlacionar el plot con lo que vive en la MCU.

        // vfd_set_frequency_mhz:
        phase_inc = (uint64_t)fo_mHz << 32 / ((uint64_t)FS_HZ * 1000ULL);

        // vfd_set_amplitude_q15:
        amp_ccr   = ((uint32_t)amp_q15 * (PWM_ARR / 2U)) >> 15;

        // vfd_set_offset_ccr:
        offset    = off_ccr;                 // sin transformacion
    """
    fo_mHz    = int(round(fo_hz * 1000))
    phase_inc = ((fo_mHz << 32) // (FS_HZ * 1000)) & 0xFFFFFFFF
    amp_ccr   = (amp_q15 * (PWM_ARR // 2)) >> 15
    return {
        "fo_mHz":    fo_mHz,
        "phase_inc": phase_inc,
        "amp_q15":   amp_q15,
        "amp_ccr":   amp_ccr,
        "offset":    offset_ccr,
    }

def plot_dds(fo_hz, amp_q15, offset_ccr):
    p      = firmware_params(fo_hz, amp_q15, offset_ccr)
    t, ccr = dds_simulate(fo_hz, amp_q15, offset_ccr)
    duty   = 100.0 * ccr / (PWM_ARR + 1)

    # Log de los parametros tal como existirian en la MCU
    print(
        "[firmware-side]  "
        f"UART -> F{p['fo_mHz']} A{p['amp_q15']} O{p['offset']}    "
        f"phase_inc=0x{p['phase_inc']:08X}  amp_ccr={p['amp_ccr']} cnt  "
        f"(swing +-{p['amp_ccr']} de PWM_ARR/2={PWM_ARR//2})"
    )

    # FFT (single-sided)
    N      = len(ccr)
    X      = np.fft.rfft(ccr - ccr.mean())
    freqs  = np.fft.rfftfreq(N, d=1.0 / FS_HZ)
    mag    = (2.0 / N) * np.abs(X)

    fig, ax = plt.subplots(2, 1, figsize=(10, 7))
    ax[0].plot(t * 1e3, duty, lw=1.2)
    ax[0].set_xlabel("Time [ms]")
    ax[0].set_ylabel("Duty [%]")
    ax[0].set_title(
        f"VFD output  fo={fo_hz} Hz  "
        f"amp_q15={amp_q15}/32767 ({100*amp_q15/Q15_MAX:.1f}%) "
        f"-> amp_ccr={p['amp_ccr']}/{PWM_ARR//2}  "
        f"offset={offset_ccr}/{PWM_ARR} ({100*offset_ccr/(PWM_ARR+1):.1f}%)  "
        f"fc={FS_HZ/1000:.0f} kHz"
    )
    ax[0].grid(True, ls="--", alpha=0.5)

    fmax = min(10 * fo_hz, FS_HZ / 2)
    mask = freqs <= fmax
    ax[1].stem(freqs[mask], mag[mask], markerfmt="C1o", linefmt="C1-", basefmt="none")
    ax[1].set_xlabel("Frequency [Hz]")
    ax[1].set_ylabel("Magnitude [CCR counts]")
    ax[1].set_title(f"FFT  (zoom 0..{fmax:.0f} Hz)")
    ax[1].grid(True, ls="--", alpha=0.5)

    plt.tight_layout()
    plt.show()

# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    print(f"PWM ARR={PWM_ARR}  fs/fc={FS_HZ} Hz  (carrier period={CARRIER_PERIOD_US} us)")
    q15 = build_sine_q15()
    write_lut_c(q15)

    # 1) Lineal a 100%: con offset centrado, amp_q15=32767 -> swing = +-ARR/2,
    #    CCR oscila entre 0 y ARR sin recorte. Forma de onda perfectamente sinusoidal.
    plot_dds(fo_hz=50, amp_q15=Q15_MAX, offset_ccr=(PWM_ARR + 1) // 2)

    # 2) Saturado por offset descentrado: amp_q15=32767 (swing +-1199) y
    #    offset 75% del ARR (=1800). El pico superior pide ccr=2999 (> ARR=2399)
    #    -> recorta arriba; el valle inferior queda en 601, no recorta. Se ve
    #    el "techo plano" en el tiempo y armónicos pares en la FFT.
    plot_dds(fo_hz=50, amp_q15=Q15_MAX, offset_ccr=(PWM_ARR * 3) // 4)